### ISSUE TITLE
[운영체제_쉬운코드] 1강 - 꼬리 질문

### ISSUE THREAD

**Issue by cyj199637** [cyj199637/TIL#1]
### 1. 프로세스 간 컨텍스트 스위칭은 어떻게 일어나는가?

**1.1 프로세스는 언제 생성되는가?**

**1.2 프로세스 간 데이터 공유는 어떻게 일어나는가?**

<br/>
        
### 2. 스레드 간 컨텍스트 스위칭은 어떻게 일어나는가?

~~**2.1 스레드 간 데이터 공유는 어떻게 일어나는가?**~~

**2.2 스레드 간 스택 영역을 공유하지 않는 이유는 무엇인가?**

<br/>

### 3. 컨텍스트 스위칭은 누가 어떻게 관리하는가?

**Comment by ohtaeg** [comment]
1.2 질문을 역으로 `프로세스 간 데이터 공유는 왜 힘든걸까?` 를 같이 고민해도 좋을 것 같습니다 ㅎㅎ
